<a href="https://colab.research.google.com/github/Carotobonb/intro-ciencia-datos-udm/blob/main/tareas/01-python/tarea_01_python_numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tarea 01 — Python y NumPy

**Instrucciones:** Completa cada celda de código con tu respuesta. No modifiques las celdas de texto.  
Cada pregunta indica exactamente qué debes escribir.

---
## Parte 1 — Python básico

**P1.** Crea una variable llamada `nombre` con tu nombre, y otra llamada `edad` con tu edad.  
Luego imprime el mensaje: `Hola, me llamo Ana y tengo 22 años.` (con tus datos).

In [1]:
# Tu respuesta aquí
nombre = "Carolina"
edad = 28
print(f"Hola, me llamo {nombre} y tengo {edad} años")


Hola, me llamo Carolina y tengo 28 años


**P2.** Dada la lista `numeros = [10, 25, 3, 47, 8, 15]`:  
- Imprime el primer y el último elemento.  
- Imprime los tres primeros elementos usando slicing.  
- Agrega el número `99` al final de la lista.

In [2]:
numeros = [10, 25, 3, 47, 8, 15]

# Tu respuesta aquí
print(f"Primer elemento {numeros[0]} y el ultimo elemento {numeros[-1]}")
print(numeros[0:3])
numeros.append(99)
print(numeros)


Primer elemento 10 y el ultimo elemento 15
[10, 25, 3]
[10, 25, 3, 47, 8, 15, 99]


**P3.** Dado el diccionario `estudiante` con las llaves `nombre`, `carrera` y `promedio`,  
escribe un `if` que imprima `"Aprobado"` si el promedio es mayor o igual a 6, y `"Reprobado"` si no.

In [3]:
estudiante = {"nombre": "Carlos", "carrera": "Sistemas", "promedio": 7.5}

# Tu respuesta aquí
if estudiante["promedio"] >= 6:
    print("Aprobado")
else:
    print("Reprobado")

Aprobado


**P4.** Crea una función llamada `calcular_area` que reciba `base` y `altura` y devuelva el área de un triángulo (`base * altura / 2`).  
Llama la función con `base=5` y `altura=8` e imprime el resultado.

In [4]:
# Tu respuesta aquí
def calcular_area(base, altura):
  resultado = (base * altura) / 2
  return resultado
print(calcular_area(5,4))


10.0


**P5.** Usa una **list comprehension** para crear una lista con los cuadrados de los números del 1 al 10.  
Imprime la lista resultante.

In [5]:
# Tu respuesta aquí
lista = [x**2 for x in range(1,11)]
print(lista)


[1, 4, 9, 16, 25, 36, 49, 64, 81, 100]


---
## Parte 2 — NumPy

In [6]:
import numpy as np

**P6.** Crea los siguientes arreglos e imprime su `shape` y `dtype`:  
- Un arreglo con los valores `[1.5, 2.5, 3.5, 4.5]`  
- Una matriz de ceros de 3 filas × 4 columnas  
- Un arreglo con 6 valores igualmente espaciados entre 0 y 1 (usando `linspace`)

In [7]:
# Tu respuesta aquí
# 1 arreglo con valores
arr1 = np.array([1.5, 2.5, 3.5, 4.5])
print("Shape:", arr1.shape)
print("Dtype:", arr1.dtype)
print(arr1)

# 2 arreglo ceros
arr2 = np.zeros((3,4))
print("Shape:", arr2.shape)
print("Dtype:", arr2.dtype)
print(arr2)

# 3. Arreglo con 6 valores entre 0 y 1
arr3 = np.linspace(0, 1, 6)
print("Linspace:")
print("Shape:", arr3.shape)
print("Dtype:", arr3.dtype)
print(arr3)


Shape: (4,)
Dtype: float64
[1.5 2.5 3.5 4.5]
Shape: (3, 4)
Dtype: float64
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
Linspace:
Shape: (6,)
Dtype: float64
[0.  0.2 0.4 0.6 0.8 1. ]


**P7.** Dado el arreglo `a = np.arange(1, 13)`, usa `reshape` para convertirlo en una matriz de 3 × 4.  
Luego imprime el valor máximo, el valor mínimo y la posición (índice) del máximo.

In [8]:
a = np.arange(1, 13)

# Tu respuesta aquí
matriz = a.reshape(3, 4)
print("Matriz:", matriz)

# Valores requeridos
print("max_val:", matriz.max())
print("min_val:", matriz.min())
print("pos_max:", np.argmax(matriz))

Matriz: [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]
max_val: 12
min_val: 1
pos_max: 11


**P8.** Crea dos arreglos de 5 elementos con `np.random.randint` (valores entre 1 y 20).  
Súmalos, réstalos y multiplícalos elemento por elemento. Imprime cada resultado.

In [9]:
# Tu respuesta aquí
a = np.random.randint(1, 21, 5)
b = np.random.randint(1, 21, 5)

print("Arreglo a:", a)
print("Arreglo b:", b)

# Operaciones
suma = a + b
resta = a - b
multiplicacion = a * b

print("Suma:", suma)
print("Resta:", resta)
print("Multiplicación:", multiplicacion)


Arreglo a: [ 3 19 17  9 15]
Arreglo b: [13  1 15  2  9]
Suma: [16 20 32 11 24]
Resta: [-10  18   2   7   6]
Multiplicación: [ 39  19 255  18 135]


**P9.** Dado el arreglo `notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])`,  
usa **indexación booleana** para obtener solo las notas mayores o iguales a 6. Imprime el resultado.

In [10]:
notas = np.array([8.5, 6.0, 9.2, 4.3, 7.8, 5.5, 10.0, 3.1])

# Tu respuesta aquí
notas_may = notas >=6
print(notas[notas_may])


[ 8.5  6.   9.2  7.8 10. ]
